simplify inputs

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,11 +4,6 @@ author: Jon Jensen
 inputs:
   uses:
     description: Action reference or path, e.g. `actions/setup-node@v3`
-    required: true
-  with:
-    description: 'JSON-ified `inputs` for the action, e.g. `{"node-version": "18"}`'
-    required: false
-    default: "{}"
 outputs:
   outputs:
     description: 'JSON-ified `outputs` from the action, e.g. `{"node-version": "v18.12.0", "cache-hit": true}`'
@@ -17,8 +12,14 @@ runs:
   using: composite
   steps:
     - name: Setup
+      env:
+        dynamic_uses: ${{ inputs['$uses'] || inputs.uses }}
       shell: bash
       run: |
+        if [[ -z $dynamic_uses ]]; then
+          echo '::error::Missing required input "uses" (or "$uses")'
+          exit 1
+        fi
         mkdir -p ./.tmp-dynamic-uses &&
         cat <<'DYNAMIC_USES_EOF' >./.tmp-dynamic-uses/action.yml
         outputs:
@@ -31,8 +32,8 @@ runs:
             shell: bash
           - name: Run
             id: run
-            uses: ${{ inputs.uses }}
-            with: ${{ inputs.with || '{}' }}
+            uses: ${{ toJSON(env.dynamic_uses) }}
+            with: ${{ toJSON(inputs) }}
         DYNAMIC_USES_EOF
     - name: Run
       id: run
