switch env-outputs logic to js

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -119,41 +119,65 @@ jobs:
         with:
           expected: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
           actual: ${{ env.A_Z }}
-      - name: Test env outputs with onconflict=overwrite
+      - name: Test env outputs with on-conflict=overwrite
         uses: ./.
         env:
           overwrite_echo: uh-oh
         with:
           uses: ./.github/actions/echo
-          env-outputs-onconflict: overwrite
+          env-outputs-on-conflict: overwrite
           env-outputs-prefix: overwrite_
       - uses: ./.github/actions/assert-equal
         with:
           expected: 🙊
           actual: ${{ env.overwrite_echo }}
-      - name: Test env outputs with onconflict=preserve
+      - name: Test env outputs with on-conflict=preserve
         uses: ./.
         env:
           preserve_echo: uh-oh
         with:
           uses: ./.github/actions/echo
-          env-outputs-onconflict: preserve
+          env-outputs-on-conflict: preserve
           env-outputs-prefix: preserve_
       - uses: ./.github/actions/assert-equal
         with:
           expected: "" # blank, since it's preserved (it was only "uh-oh" within the step)
           actual: ${{ env.preserve_echo }}
-      - name: Test env outputs with onconflict=error
-        id: env-outputs-with-onconflict-error
+      - name: Test env outputs with on-conflict=error
+        id: env-outputs-with-on-conflict-error
         continue-on-error: true
         uses: ./.
         env:
           error_echo: uh-oh
         with:
           uses: ./.github/actions/echo
-          env-outputs-onconflict: error
+          env-outputs-on-conflict: error
           env-outputs-prefix: error_
       - uses: ./.github/actions/assert-equal
         with:
           expected: failure
-          actual: ${{ steps.env-outputs-with-onconflict-error.outcome }}
+          actual: ${{ steps.env-outputs-with-on-conflict-error.outcome }}
+  check-dist:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+      - name: Set up node
+        uses: actions/setup-node@v6
+        with:
+          node-version: 24
+          cache: 'npm'
+          cache-dependency-path: set-env-vars
+      - name: Install dependencies
+        run: npm ci
+        working-directory: set-env-vars
+      - name: Build dist
+        run: npm run build
+        working-directory: set-env-vars
+      - name: Check dist
+        run: |
+          git diff --exit-code || {
+            echo "::error::dist is not up to date. Did you forget to run 'npm run build'?";
+            exit 1;
+          }
+        working-directory: set-env-vars
